# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rkeepass_wrappers", use_symbols = TRUE, package_name = "rkeepass")

#' @usage NULL
#' @useDynLib rkeepass, .registration = TRUE
NULL

kdbx_read_impl <- function(path, password, keyfile) .Call(wrap__kdbx_read_impl, path, password, keyfile)


# nolint end
